#!/bin/bash

#cd ~/development
unzip ~/Downloads/flutter_macos_1.17.5-stable.zip

export PATH="$PATH:$PWD/flutter/bin"
# enable web
flutter channel beta
flutter upgrade
flutter config --enable-web
flutter devices # check web devices

flutter precache
flutter doctor

# add support for existed project
cd my_app # goto your project folder
flutter create . # web will be enabled for this project
